kind: ReplicaSet
apiVersion: apps/v1
metadata:
  name: simple-wallet-7cf976d999
  namespace: default
  selfLink: /apis/apps/v1/namespaces/default/replicasets/simple-wallet-7cf976d999
  uid: 12dce6a9-af40-44df-8dfa-f13e6924ece7
  resourceVersion: '11342'
  generation: 1
  creationTimestamp: '2020-10-01T08:27:05Z'
  labels:
    app: simple-wallet
    pod-template-hash: 7cf976d999
  annotations:
    deployment.kubernetes.io/desired-replicas: '1'
    deployment.kubernetes.io/max-replicas: '2'
    deployment.kubernetes.io/revision: '1'
  ownerReferences:
    - apiVersion: apps/v1
      kind: Deployment
      name: simple-wallet
      uid: 9c45fc37-2153-4342-aece-dfa4fa8a74f5
      controller: true
      blockOwnerDeletion: true
  managedFields:
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2020-10-01T09:10:21Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:deployment.kubernetes.io/desired-replicas': {}
            'f:deployment.kubernetes.io/max-replicas': {}
            'f:deployment.kubernetes.io/revision': {}
          'f:labels':
            .: {}
            'f:app': {}
            'f:pod-template-hash': {}
          'f:ownerReferences':
            .: {}
            'k:{"uid":"9c45fc37-2153-4342-aece-dfa4fa8a74f5"}':
              .: {}
              'f:apiVersion': {}
              'f:blockOwnerDeletion': {}
              'f:controller': {}
              'f:kind': {}
              'f:name': {}
              'f:uid': {}
        'f:spec':
          'f:replicas': {}
          'f:selector':
            'f:matchLabels':
              .: {}
              'f:app': {}
              'f:pod-template-hash': {}
          'f:template':
            'f:metadata':
              'f:labels':
                .: {}
                'f:app': {}
                'f:pod-template-hash': {}
            'f:spec':
              'f:containers':
                'k:{"name":"simple-wallet"}':
                  .: {}
                  'f:image': {}
                  'f:imagePullPolicy': {}
                  'f:name': {}
                  'f:resources': {}
                  'f:terminationMessagePath': {}
                  'f:terminationMessagePolicy': {}
              'f:dnsPolicy': {}
              'f:restartPolicy': {}
              'f:schedulerName': {}
              'f:securityContext': {}
              'f:terminationGracePeriodSeconds': {}
        'f:status':
          'f:availableReplicas': {}
          'f:fullyLabeledReplicas': {}
          'f:observedGeneration': {}
          'f:readyReplicas': {}
          'f:replicas': {}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-wallet
      pod-template-hash: 7cf976d999
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: simple-wallet
        pod-template-hash: 7cf976d999
    spec:
      containers:
        - name: simple-wallet
          image: 'docker.io/library/simple-wallet:0.0.1-SNAPSHOT'
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
status:
  replicas: 1
  fullyLabeledReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  observedGeneration: 1
